import Navbar from '@/components/Navbar'
import './globals.css'
import Footer from '@/components/Footer'
import ScrollToTop from '@/components/ScrollToTop'
import Head from 'next/head'


export const metadata = {
  title: 'Pixarzo | Home',
  description: 'Generated by create next app',
  faviconPng: '/favicon.png',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" type="image/png" sizes="32x32" href={metadata.faviconPng} />
      </Head>

      <body className='font-JakartaFont'>
        <Navbar/>
        {children}
         <ScrollToTop/>
        <Footer/>
        </body>
    </html>
  )
}
